---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
platforms:
  - name: vpnpeer-setup-instance
    image: ubuntu:xenial
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: playbook.yml
verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: true
