---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
platforms:
  - name: vpnpeer-validator-node
    image: ubuntu:bionic
    volumes:
      - /dev/net/tun:/dev/net/tun
    capabilities:
      - NET_ADMIN
    groups:
      - validator
  - name: vpnpeer-public-node
    image: ubuntu:bionic
    volumes:
      - /dev/net/tun:/dev/net/tun
    capabilities:
      - NET_ADMIN
    groups:
      - public
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: playbook.yml
  inventory:
    host_vars:
      vpnpeer-validator-node:
        vpnpeer_address: 10.0.0.1
        vpn_private_key: vpn_secret1
        vpnpeer_cidr_suffix: 24
        vpn_public_key: vpn_public1
      vpnpeer-public-node:
        vpnpeer_address: 10.0.0.2
        vpn_private_key: vpn_secret2
        vpnpeer_cidr_suffix: 24
        vpn_public_key: vpn_public2
verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: true
