---
# tasks file for polkadot-public
- name: create polkadot service file
  template:
    src: polkadot.service.j2
    dest: /etc/systemd/system/polkadot.service
    owner: root
    group: root
    mode: 0600

- name: restart polkadot service
  shell: |
    set -o pipefail
    systemctl stop polkadot.service || true

    if [ -f /usr/local/bin/polkadot-new ]; then
      cp /usr/local/bin/polkadot-new /usr/local/bin/polkadot
      chown polkadot:polkadot /usr/local/bin/polkadot
      chmod a+x /usr/local/bin/polkadot
    fi
    systemctl daemon-reload
    systemctl start polkadot.service
  args:
    executable: /bin/bash
  changed_when: False
