---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
platforms:
  - name: polkadot-common-instance
    image: ubuntu:bionic
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: playbook.yml
  inventory:
    host_vars:
      polkadot-common-instance:
        polkadot_binary_url: 'https://github.com/w3f/polkadot/releases/download/v0.7.31/polkadot'
        polkadot_binary_checksum: 'sha256:e091c5a58348a2bc62653eed0af66ee0bfd532c45dbf1bcca5dbe93e6dbc3baa'
verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: true
