---
- name: create VPN configuration file
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: 0600

- name: recreate wg interface
  shell: |
    set -o pipefail
    wg-quick down wg0 || true
  args:
    executable: /bin/bash
  changed_when: false

- name: start VPN setup service
  systemd:
    name: wg-quick@wg0
    state: restarted
    daemon_reload: yes
    enabled: yes
  changed_when: false
