---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
platforms:
  - name: common-validator-node
    image: ubuntu:bionic
    groups:
      - validator
  - name: common-public-node
    image: ubuntu:bionic
    groups:
      - public
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: playbook.yml
verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: true
